---
name: lite-licence-application
namespace: lite
scm: git@github.com:uktrade/lite-licence-application.git
environments:
  - environment: dev
    type: gds
    region: eu-west-2
    app: dit-staging/lite-dev/lite-licence-application-dev
    vars:
      - JAVA_EXTENSION: zip
      - NEXUS_PATH: lite-builds-raw/lite-licence-application/lite-licence-application
      - USE_NEXUS: true
    secrets: true
    run: []
  - environment: uat
    type: gds
    region: eu-west-2
    app: dit-staging/lite-uat/lite-licence-application-uat
    vars:
      - JAVA_EXTENSION: zip
      - NEXUS_PATH: lite-builds-raw/lite-licence-application/lite-licence-application
      - USE_NEXUS: true
    secrets: true
    run: []
  - environment: staging
    type: gds
    region: eu-west-2
    app: dit-staging/lite-staging/lite-licence-application-staging
    vars:
      - JAVA_EXTENSION: zip
      - NEXUS_PATH: lite-builds-raw/lite-licence-application/lite-licence-application
      - USE_NEXUS: true
    secrets: true
    run: []
  - environment: prod
    type: gds
    region: eu-west-2
    app: dit-services/lite/lite-licence-application
    vars:
      - JAVA_EXTENSION: zip
      - NEXUS_PATH: lite-builds-raw/lite-licence-application/lite-licence-application
      - USE_NEXUS: true
    secrets: true
    run: []
