---
name: lite-application-service
namespace: lite
scm: git@github.com:uktrade/lite-application-service.git
environments:
  - environment: dev
    type: gds
    region: eu-west-2
    app: dit-staging/lite-dev/lite-application-service-dev
    vars: []
    secrets: false
    run: []
  - environment: staging
    type: gds
    region: eu-west-2
    app: dit-staging/lite-staging/lite-application-service-staging
    vars: []
    secrets: false
    run: []
  - environment: uat
    type: gds
    region: eu-west-2
    app: dit-staging/lite-uat/lite-application-service-uat
    vars: []
    secrets: false
    run: []
  - environment: prod
    type: gds
    region: eu-west-2
    app: dit-services/lite/lite-application-service
    vars: []
    secrets: false
    run: []
